# TODO: Load branch like deps-corestyles-v4-28 but off of main
FROM taccwma/core-cms:v4.36.10

WORKDIR /code

COPY /src/taccsite_custom /code/taccsite_custom
COPY /src/taccsite_cms /code/taccsite_cms
