# Generated by Django 4.2.9 on 2025-08-12 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bootstrap4_tabs', '0002_auto_20180610_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootstrap4TabItemModel',
            fields=[
                ('bootstrap4tabitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bootstrap4_tabs.bootstrap4tabitem')),
                ('tab_image', filer.fields.image.FilerImageField(blank=True, help_text='Optional image to display in the tab title for slideshow navigation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Tab Image/Thumbnail')),
            ],
            options={
                'proxy': False,
            },
            bases=('bootstrap4_tabs.bootstrap4tabitem',),
        ),
    ]
