# Generated by Django 4.2.9 on 2025-08-13 23:46

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('taccsite_bootstrap4_tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabimageextension',
            name='tab_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Optional image to display in the tab title for slideshow navigation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image/Thumbnail'),
        ),
    ]
